SHOW CHARACTER SET
SHOW [FULL] COLUMNS FROM nom_table [FROM nom_bdd]
SHOW DATABASES
SHOW GRANTS [FOR utilisateur]
SHOW INDEX FROM nom_table [FROM nom_bdd]
SHOW PRIVILEGES
SHOW PROCEDURE STATUS
SHOW [FULL] TABLES [FROM nom_bdd]
SHOW TRIGGERS [FROM nom_bdd]
SHOW [GLOBAL | SESSION] VARIABLES
SHOW WARNINGS




SELECT CONSTRAINT_SCHEMA, CONSTRAINT_NAME, TABLE_NAME, CONSTRAINT_TYPE
FROM TABLE_CONSTRAINTS;
