val data = Array(("Ajaccio",653    ),
                 ("Angers",690     ),
                 ("Angoulème",826  ),
                 ("Besançon",1088  ),
                 ("Biarritz",1474  ),
                 ("Bordeaux",947   ),
                 ("Brest",1157     ),
                 ("Caen",713       ),
                 ("Clermont-Fd",571),
                 ("Dijon",734      ),
                 ("Embrun",698     ),
                 ("Grenoble",1005  ),
                 ("Lille",612      ),
                 ("Limoges",910    ),
                 ("Lyon",828       ),
                 ("Marseille",533  ),
                 ("Montpellier",736),
                 ("Nancy",721      ),
                 ("Nantes",809     ),
                 ("Nice",868       ),
                 ("Nîmes",680      ),
                 ("Orléans",621    ),
                 ("Paris",624      ),
                 ("Perpignan",629  ),
                 ("Poitiers",702   ),
                 ("Reims",575      ),
                 ("Rennes",634     ),
                 ("Rouen",716      ),
                 ("St-Quentin",684 ),
                 ("Strasbourg",719 ),
                 ("Toulon",837     ),
                 ("Toulouse",656   ),
                 ("Tours",687      ),
                 ("Vichy",761      ))
val precAnnuelles = sc.parallelize(data)
